version: '3'

services:
  frontend:
    build: ./frontend
    #command: npm run start
    command: serve -s build -l 3000
    restart: unless-stopped
    ports:
      - "3000:3000"
    #stdin_open: true
    #tty: true
    #volumes:
      #- ./frontend/src:/usr/src/app/src   comments were for DEV
