version: '3'

services:
  frontend:
    build: ./frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - myproject-network

  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://mydockerproject.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
    networks:
      - myproject-network

  api_db:
    image: mongo:latest
    networks:
      - myproject-network

  englishcards:
    build: ./english-cards
    command: serve -s build -l 3002
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
      - myproject-network

networks:
  myproject-network:
    driver: bridge