version: '3'

services:
  frontend:
    build: ./frontend
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
